# [环境变量参考地址](https://dysoncheng.github.io/PalWorldSettingGenerator/setting.html)
# [官方：技术指南、教程、环境变量](https://tech.palworldgame.com/)
version: "3.9"
services:
  palworld-dedicated-server:
    #build: .
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: always
    network_mode: bridge
    ports:
      - target: 8211 # Gamerserver port inside of the container
        published: 8211 # Gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # RCON port inside of the container
        published: 25575 # RCON port on your host
        protocol: tcp
        mode: host
    environment:
      - TZ=Asia/Shanghai # 时区
      - ALWAYS_UPDATE_ON_START=true # 启动服务时，更新服务器
      - MULTITHREAD_ENABLED=true # 开启多线程
      - COMMUNITY_SERVER=true # 社区服务器模式
      - BACKUP_ENABLED=true # 服务器备份（对应到volume内的文件）
      - BACKUP_CRON_EXPRESSION=0 * * * * # 备份轮训Cron表达式
      - NETSERVERMAXTICKRATE=120 # 网络最大心跳延迟（30 - 120，默认120）
      - DIFFICULTY=None # 游戏模式（None、Normal、Difficult）
      - DAYTIME_SPEEDRATE=1.000000 # 白天时间速率
      - NIGHTTIME_SPEEDRATE=1.000000 # 夜间时间速率
      - EXP_RATE=1.000000 # 经验率
      - PAL_CAPTURE_RATE=1.000000 # 捕获率
      - PAL_SPAWN_NUM_RATE=1.000000 # 生成率
      - PAL_DAMAGE_RATE_ATTACK=1.000000 # 伤害率
      - PAL_DAMAGE_RATE_DEFENSE=1.000000 # 防御率
      - PLAYER_DAMAGE_RATE_ATTACK=1.000000 # 玩家伤害率
      - PLAYER_DAMAGE_RATE_DEFENSE=1.000000 # 玩家防御率
      - PLAYER_STOMACH_DECREASE_RATE=1.000000 # 玩家饥饿率
      - PLAYER_STAMINA_DECREACE_RATE=1.000000 # 玩家耐力减少率
      - PLAYER_AUTO_HP_REGENE_RATE=1.000000 # 玩家自动生命恢复率
      - PLAYER_AUTO_HP_REGENE_RATE_IN_SLEEP=1.000000 # 玩家睡眠自动生命恢复率
      - PAL_STOMACH_DECREACE_RATE=1.000000 # 帕鲁饥饿率
      - PAL_STAMINA_DECREACE_RATE=1.000000 # 帕鲁耐力减少率
      - PAL_AUTO_HP_REGENE_RATE=1.000000 # 帕鲁HP恢复率
      - PAL_AUTO_HP_REGENE_RATE_IN_SLEEP=1.000000 # 帕鲁睡眠HP恢复率
      - BUILD_OBJECT_DAMAGE_RATE=1.000000 # 对建筑伤害率
      - BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=1.000000 # 建筑恶化率
      - COLLECTION_DROP_RATE=1.000000
      - COLLECTION_OBJECT_HP_RATE=1.000000
      - COLLECTION_OBJECT_RESPAWN_SPEED_RATE=1.000000
      - ENEMY_DROP_ITEM_RATE=1.000000
      - DEATH_PENALTY=All
      - ENABLE_PLAYER_TO_PLAYER_DAMAGE=false
      - ENABLE_FRIENDLY_FIRE=false
      - ENABLE_INVADER_ENEMY=true
      - ACTIVE_UNKO=false
      - ENABLE_AIM_ASSIST_PAD=true
      - ENABLE_AIM_ASSIST_KEYBOARD=false
      - DROP_ITEM_MAX_NUM=3000
      - DROP_ITEM_MAX_NUM_UNKO=100
      - BASE_CAMP_MAX_NUM=128
      - BASE_CAMP_WORKER_MAXNUM=15
      - DROP_ITEM_ALIVE_MAX_HOURS=1.000000
      - AUTO_RESET_GUILD_NO_ONLINE_PLAYERS=false
      - AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS=72.000000
      - GUILD_PLAYER_MAX_NUM=20
      - PAL_EGG_DEFAULT_HATCHING_TIME=72.000000
      - WORK_SPEED_RATE=1.000000
      - IS_MULTIPLAY=false
      - IS_PVP=false
      - CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP=false
      - ENABLE_NON_LOGIN_PENALTY=true
      - ENABLE_FAST_TRAVEL=true
      - IS_START_LOCATION_SELECT_BY_MAP=true
      - EXIST_PLAYER_AFTER_LOGOUT=false
      - ENABLE_DEFENSE_OTHER_GUILD_PLAYER=false
      - COOP_PLAYER_MAX_NUM=4 # 最大组队玩家
      - MAX_PLAYERS=32 # 最大玩家
      - SERVER_NAME=xiaoqinvar-test-###RANDOM###
      - SERVER_DESCRIPTION=testing docker build sever.
      - ADMIN_PASSWORD=root1234 # 管理员密码
      - SERVER_PASSWORD=1234567890 # 服务器进入密码
      - PUBLIC_PORT=8211
      - PUBLIC_IP=# 默认自动识别
      - RCON_ENABLED=true # 启用RCON
      - RCON_PORT=25575
      - REGION=
      - USEAUTH=true
      - BAN_LIST_URL=https://api.palworldgame.com/api/banlist.txt
    volumes:
      - /home/ubuntu/docker/palworld:/palworld

  rcon:
    image: outdead/rcon:latest
    entrypoint: ["/rcon", "-a", "106.75.233.89:25575", "-p", "root1234"]
    profiles: ["rcon"]
