listening-port=3478
# 为rfc5780提供的备用端口
alt-listening-port=3479

listening-ip=0.0.0.0
listening-ip=127.0.0.1

external-ip=116.62.107.125/0.0.0.0
external-ip=116.62.107.125/127.0.0.1

# 只启用STUN服务，不启用TURN服务
stun-only

# TURN 中继服务，表示中继流量从哪个本机IP发出去
# relay-ip=0.0.0.0
# relay-ip=127.0.0.1

# 启用OTHER-ADDRESS属性
rfc5780
no-auth
# 不需要TURN中继服务，关闭TURN TCP监听
no-tcp
# 不需要TURN中继服务，关闭tls + TURN tcp的监听
no-tls
# 关闭STUN/TURN UDP + tls的监听。一般支持dtls客户端会先进行DTLS握手获取会话密钥，再进行STUN/TURN消息传输
no-dtls
# 关闭coturn的命令行接口
no-cli
# 一般客户端都期望有一个fingerprint属性，用于校验消息是否完整
fingerprint
# 详细的日志
verbose
# 表示日志输出到标准输出，而不是写到日志文件中，对docker logs友好
log-file=stdout