# frpc 连接frps的配置
serverAddr = "服务器IP"
serverPort = 7000
auth.token = "令牌"

# 默认为true，启用TCP多路复用，frps.toml必须保持一致frpc.toml
transport.tcpMux = true

[[proxies]]
# ssh内网穿透
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 19006

[[proxies]]
# xtcp SSH P2P连接（这里是remote client配置，visitor配置请参考frpc-visitor.toml配置文件）
name = "p2p_ssh"
type = "xtcp"
secretKey = "abcdefg"
localIP = "127.0.0.1"
localPort = 22