bindAddr = "0.0.0.0" # 服务端监听地址，用于接收 frpc 的连接，默认监听 0.0.0.0。
bindPort = 7000 # 服务端监听端口，默认值为 7000。
vhostHTTPPort = 19005 # 访问该端口转发到内网HTTP
enablePrometheus = true # 启用普普罗米修斯监控（需要同时启用了 webServer 后才会生效）

# 配置文件写法
# ClientCommonConfig可以直接写配置
# transport 属于ClientTransportConfig，而poolCount属于其子属性
# 所以需要用"transport.poolCount"表示
auth.token = "token-value"

# web 面板
webServer.addr = "0.0.0.0" # web控制台允许访问的ip
webServer.port = 19003 # web面板的端口
webServer.user = "username"
webServer.password = "123456"
