services:
  certd:
    image: registry.cn-shenzhen.aliyuncs.com/handsfree/certd:latest
    container_name: certd
    restart: unless-stopped # 自动重
    volumes:
      - $PWD:/app/data
    ports: # 端口映射
      - "7001:7001"
      - "7002:7002"
    # ⚠️如果出现getaddrinfo ENOTFOUND错误，可以尝试设置dns
#    dns:
#         阿里云公共dns
#      - 223.5.5.5
#      - 223.6.6.6
#         腾讯云DNS
#      - 119.29.29.29
#      - 182.254.116.116
#         谷歌公共dns
#      - 8.8.8.8
#      - 8.8.4.4

#    extra_hosts:
#        本地域名解析，局域网内使用
#      - "localdomain.comm:192.168.1.3"

    environment:
#     设置环境变量即可自定义certd配置
#     配置项见： https://github.com/certd/certd/blob/v2/packages/ui/certd-server/src/config/config.default.ts
#     配置规则： certd_ + 配置项, 点号用_代替
#       如果忘记管理员密码，可以设置为true，重启之后，管理员密码将改成123456，然后请及时修改回false
      - certd_system_resetAdminPasswd=false
#        使用postgresql数据库
#      - certd_flyway_scriptDir=./db/migration-pg                        # 升级脚本目录
#      - certd_typeorm_dataSource_default_type=postgres                  # 数据库类型
#      - certd_typeorm_dataSource_default_host=localhost                 # 数据库地址
#      - certd_typeorm_dataSource_default_port=5433                      # 数据库端口
#      - certd_typeorm_dataSource_default_username=postgres              # 用户名
#      - certd_typeorm_dataSource_default_password=yourpasswd            # 密码
#      - certd_typeorm_dataSource_default_database=certd                 # 数据库名

#    启用ipv6网络
#    networks:
#      - ip6net
#networks:
#  ip6net:
#    enable_ipv6: true
#    ipam:
#      config:
#        - subnet: 2001:db8::/64